project:
  type: book
  output-dir: ../_build/book


book:
  title: "EMSC - Get Going with Python "
  author: 
    - "Louis Moresi"
    - "Andrew Valentine"
  date: "06/03/2024"
  bread-crumbs: True
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
    - part: "Basic Language Skills"
      chapters:
        - Basics/Intro.qmd
        - Basics/Ex1-GettingStartedWithPython.qmd
        - Basics/Ex2-VariablesAndFunctions.qmd
        - Basics/Ex8-ReadWriteFiles.qmd

    - part: "Advanced Language Skills"
      chapters:
        - Advanced/Intro.qmd

    - part: "Next steps: Becoming a Code Developer"
      chapters:
        - DevSkills/Intro.qmd
    
    # - part: "Notebooks"
    #   chapters:
    #   - Notebooks/Introduction.qmd
    #   - Notebooks/Ex01/Ex1-GettingStartedWithJupyter.qmd

    # - part: "Slides"
    #   chapters:
    #     - LectureSlides/Lecture1.qmd

    - part: "Work in Progress"
      chapters:
      - _WIP/Test_Pyodide.qmd

  # appendices:
  #   - Notebooks/BinderLandingPage.qmd
  #   - Notebooks/TestNB1.ipynb
  #   - Notebooks/TestQMD_NB1.qmd

  navbar:
    search: true
    logo: Images/ANU-logo.jpg
    background: "white"
    foreground: "#C58812" # ANU honey colour

  sidebar:
    # logo: Images/COS-EarthSciences-800.jpg
    # logo: Images/ANU-logo.jpg
    background: "white"
    # foreground: "#C58812" # ANU honey colour


bibliography: references.bib

execute: 
  enabled: false
  
format:
  html:
    theme: flatly # united / simplex
    linkcolor: "#C58812"
    number-sections: false
    number-depth: 1
    filters:
      - pyodide

    # code-links:
    #   - text: Open in Binder
    #     icon: rocket-takeoff
    #     href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-getting-going-with-python/HEAD?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd
    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-getting-going-with-python
  
  # pdf:
  #   documentclass: scrreprt



