project:
  type: book
  output-dir: ../_build/book

book:
  title: "EMSC Quarto"
  author: "Louis Moresi"
  date: "06/03/2024"
  bread-crumbs: false
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
    - part: "Details"
      chapters:
      - summary.qmd
      - references.qmd

    - part: "Slides"
      chapters:
        - LectureSlides/Lecture1.qmd

  appendices:
    - Notebooks/BinderLandingPage.qmd
    - Notebooks/TestNB1.ipynb
    - Notebooks/TestQMD_NB1.qmd

  navbar:
    search: true
    logo: Images/ANU-logo.jpg
    background: "white"
    foreground: "#C58812" # ANU honey colour

  sidebar:
    # logo: Images/COS-EarthSciences-800.jpg
    # logo: Images/ANU-logo.jpg
    background: "white"
    # foreground: "#C58812" # ANU honey colour


bibliography: references.bib

format:
  html:
    theme: flatly # united / simplex
    linkcolor: "#C58812"

    code-links:
      - text: Open in Binder
        icon: rocket-takeoff
        href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-QuartoBook/HEAD?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd
    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-QuartoBook
  
  pdf:
    documentclass: scrreprt



